"""
Scaffold templates for generating Masumi agent files with database and framework integration.
"""

import os
from typing import Optional


# Base template (no database, no framework)
BASE_TEMPLATE = '''#!/usr/bin/env python3
"""
Masumi Agent - Generated by masumi scaffold
"""
import os
from masumi import run, Config

# Define agent logic
async def process_job(identifier_from_purchaser: str, input_data: dict):
    """
    Process a job - implement your agent logic here
    
    Args:
        identifier_from_purchaser: Identifier from the purchaser
        input_data: Input data matching INPUT_SCHEMA
    
    Returns:
        Result of processing
    """
    # TODO: Implement your agent logic here
    text = input_data.get("text", "")
    return {"result": f"Processed: {text}", "purchaser": identifier_from_purchaser}

# Define input schema
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "text",
            "type": "string",
            "name": "Text Input",
            "data": {
                "description": "Text to process"
            },
            "validations": [
                {"validation": "required", "value": "true"}
            ]
        }
    ]
}

# Main entry point
if __name__ == "__main__":
    # Config and identifiers loaded from environment variables
    # Default mode is API - use --standalone flag to run standalone
    run(
        start_job_handler=process_job,
        input_schema_handler=INPUT_SCHEMA
        # config, agent_identifier, network loaded from env vars automatically
    )
'''


# Database templates
SQLITE_TEMPLATE = '''import sqlite3

# Database setup
DB_PATH = os.getenv("DB_PATH", "agent.db")

def get_db():
    """Get database connection"""
    conn = sqlite3.connect(DB_PATH)
    return conn
'''

POSTGRESQL_TEMPLATE = '''import psycopg2
from psycopg2 import pool

# Database setup
DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
    "database": os.getenv("DB_NAME", "masumi_agent"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", "")
}

# Connection pool
db_pool = None

def get_db():
    """Get database connection from pool"""
    global db_pool
    if db_pool is None:
        db_pool = psycopg2.pool.SimpleConnectionPool(1, 20, **DB_CONFIG)
    return db_pool.getconn()

def return_db(conn):
    """Return connection to pool"""
    db_pool.putconn(conn)
'''

MONGODB_TEMPLATE = '''from pymongo import MongoClient

# Database setup
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
DB_NAME = os.getenv("DB_NAME", "masumi_agent")

client = MongoClient(MONGO_URI)
db = client[DB_NAME]

def get_db():
    """Get database instance"""
    return db
'''

REDIS_TEMPLATE = '''import redis

# Redis setup
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB = int(os.getenv("REDIS_DB", "0"))

redis_client = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=REDIS_DB, decode_responses=True)

def get_redis():
    """Get Redis client"""
    return redis_client
'''


# Framework templates
LANGCHAIN_TEMPLATE = '''from langchain.llms import OpenAI
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

# Framework setup
llm = OpenAI(temperature=0.7)

# Example prompt template
prompt = PromptTemplate(
    input_variables=["text"],
    template="Process the following text: {text}"
)

chain = LLMChain(llm=llm, prompt=prompt)
'''

CREWAI_TEMPLATE = '''from crewai import Agent, Task, Crew

# Framework setup - define your agents and tasks here
# Example:
# agent = Agent(
#     role='Agent Role',
#     goal='Agent Goal',
#     backstory='Agent backstory'
# )
'''

AUTOGEN_TEMPLATE = '''from autogen import ConversableAgent

# Framework setup - define your agents here
# Example:
# agent = ConversableAgent(
#     name="agent",
#     system_message="You are a helpful assistant.",
#     llm_config={"config_list": [{"model": "gpt-4", "api_key": os.getenv("OPENAI_API_KEY")}]}
# )
'''


def _get_database_template(database: Optional[str]) -> tuple[str, str]:
    """Get database template and imports."""
    if database == "sqlite":
        return SQLITE_TEMPLATE, "import sqlite3"
    elif database == "postgresql":
        return POSTGRESQL_TEMPLATE, "import psycopg2\nfrom psycopg2 import pool"
    elif database == "mongodb":
        return MONGODB_TEMPLATE, "from pymongo import MongoClient"
    elif database == "redis":
        return REDIS_TEMPLATE, "import redis"
    else:
        return "", ""


def _get_framework_template(framework: Optional[str]) -> tuple[str, str]:
    """Get framework template and imports."""
    if framework == "langchain":
        return LANGCHAIN_TEMPLATE, "from langchain.llms import OpenAI\nfrom langchain.chains import LLMChain\nfrom langchain.prompts import PromptTemplate"
    elif framework == "crewai":
        return CREWAI_TEMPLATE, "from crewai import Agent, Task, Crew"
    elif framework == "autogen":
        return AUTOGEN_TEMPLATE, "from autogen import ConversableAgent"
    else:
        return "", ""


def _get_process_job_template(database: Optional[str], framework: Optional[str]) -> str:
    """Get process_job function template with database/framework integration."""
    db_code = ""
    framework_code = ""
    
    if database == "sqlite":
        db_code = """    # Example: Save to database
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO jobs (purchaser_id, input_data) VALUES (?, ?)",
        (identifier_from_purchaser, str(input_data))
    )
    conn.commit()
    conn.close()
"""
    elif database == "postgresql":
        db_code = """    # Example: Save to database
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO jobs (purchaser_id, input_data) VALUES (%s, %s)",
        (identifier_from_purchaser, str(input_data))
    )
    conn.commit()
    return_db(conn)
"""
    elif database == "mongodb":
        db_code = """    # Example: Save to database
    db = get_db()
    db.jobs.insert_one({
        "purchaser_id": identifier_from_purchaser,
        "input_data": input_data
    })
"""
    elif database == "redis":
        db_code = """    # Example: Cache in Redis
    redis_client = get_redis()
    redis_client.set(f"job:{identifier_from_purchaser}", str(input_data))
"""
    
    if framework == "langchain":
        framework_code = """    # Example: Use LangChain
    text = input_data.get("text", "")
    result = chain.run(text=text)
"""
    elif framework == "crewai":
        framework_code = """    # Example: Use CrewAI
    # task = Task(description=f"Process: {input_data}", agent=agent)
    # crew = Crew(agents=[agent], tasks=[task])
    # result = crew.kickoff()
    result = {"status": "processed", "data": input_data}
"""
    elif framework == "autogen":
        framework_code = """    # Example: Use AutoGen
    # result = agent.generate_reply(messages=[{"role": "user", "content": str(input_data)}])
    result = {"status": "processed", "data": input_data}
"""
    else:
        framework_code = """    # Process input
    text = input_data.get("text", "")
    result = f"Processed: {text}"
"""
    
    return f"""async def process_job(identifier_from_purchaser: str, input_data: dict):
    \"\"\"
    Process a job - integrate with database and framework here
    
    Args:
        identifier_from_purchaser: Identifier from the purchaser
        input_data: Input data matching INPUT_SCHEMA
    
    Returns:
        Result of processing
    \"\"\"
{db_code}{framework_code}
    return {{"result": result, "purchaser": identifier_from_purchaser}}
"""


def _get_init_code(database: Optional[str]) -> str:
    """Get initialization code for database tables."""
    if database == "sqlite":
        return """    # Initialize database tables if needed
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute(\"\"\"
        CREATE TABLE IF NOT EXISTS jobs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            purchaser_id TEXT,
            input_data TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    \"\"\")
    conn.commit()
    conn.close()
"""
    elif database == "postgresql":
        return """    # Initialize database tables if needed
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute(\"\"\"
        CREATE TABLE IF NOT EXISTS jobs (
            id SERIAL PRIMARY KEY,
            purchaser_id TEXT,
            input_data TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    \"\"\")
    conn.commit()
    return_db(conn)
"""
    elif database == "mongodb":
        return """    # Database collections are created automatically in MongoDB
    # No initialization needed
"""
    elif database == "redis":
        return """    # Redis doesn't require table initialization
    # No initialization needed
"""
    return ""


def scaffold(
    output_file: str = "agent.py",
    database: Optional[str] = None,
    framework: Optional[str] = None,
    interactive: bool = True
) -> None:
    """
    Generate a scaffolded Masumi agent file.
    
    Args:
        output_file: Output filename (default: "agent.py")
        database: Database choice ("sqlite", "postgresql", "mongodb", "redis", or None)
        framework: Framework choice ("langchain", "crewai", "autogen", or None)
        interactive: If True, prompt user for choices
    """
    if interactive:
        # Interactive mode - prompt user
        print("\n" + "=" * 70)
        print("Masumi Agent Scaffold")
        print("=" * 70)
        
        if output_file == "agent.py":
            user_output = input(f"\nOutput filename [{output_file}]: ").strip()
            if user_output:
                output_file = user_output
        
        if database is None:
            print("\nDatabase options:")
            print("  1. None (no database)")
            print("  2. SQLite (file-based, no setup needed)")
            print("  3. PostgreSQL (requires connection string)")
            print("  4. MongoDB (requires connection string)")
            print("  5. Redis (for caching/sessions)")
            db_choice = input("\nSelect database [1]: ").strip() or "1"
            db_map = {"1": None, "2": "sqlite", "3": "postgresql", "4": "mongodb", "5": "redis"}
            database = db_map.get(db_choice, None)
        
        if framework is None:
            print("\nFramework options:")
            print("  1. None (plain Python)")
            print("  2. LangChain (LLM orchestration)")
            print("  3. CrewAI (multi-agent framework)")
            print("  4. AutoGen (conversational AI agents)")
            fw_choice = input("\nSelect framework [1]: ").strip() or "1"
            fw_map = {"1": None, "2": "langchain", "3": "crewai", "4": "autogen"}
            framework = fw_map.get(fw_choice, None)
    
    # Generate template
    db_imports, db_template = _get_database_template(database)
    fw_imports, fw_template = _get_framework_template(framework)
    process_job_code = _get_process_job_template(database, framework)
    init_code = _get_init_code(database)
    
    # Build imports section
    imports = ["import os", "from masumi import run, Config"]
    if db_imports:
        imports.append(db_imports)
    if fw_imports:
        imports.append(fw_imports)
    
    # Build header comment
    header_parts = ["Masumi Agent - Generated by masumi scaffold"]
    if database:
        header_parts.append(f"Database: {database.capitalize()}")
    if framework:
        header_parts.append(f"Framework: {framework.capitalize()}")
    header = "\n".join([f"# {part}" for part in header_parts])
    
    # Build template
    template_parts = [
        "#!/usr/bin/env python3",
        '"""',
        "\n".join(header_parts),
        '"""',
        "\n".join(imports),
        "",
        db_template,
        "",
        fw_template,
        "",
        "# Define agent logic",
        process_job_code,
        "",
        "# Define input schema",
        'INPUT_SCHEMA = {',
        '    "input_data": [',
        '        {',
        '            "id": "text",',
        '            "type": "string",',
        '            "name": "Text Input",',
        '            "data": {',
        '                "description": "Text to process"',
        '            },',
        '            "validations": [',
        '                {"validation": "required", "value": "true"}',
        '            ]',
        '        }',
        '    ]',
        '}',
        "",
        "# Main entry point",
        "if __name__ == \"__main__\":",
        init_code,
        "    # Config and identifiers loaded from environment variables",
        "    # Default mode is API - use --standalone flag to run standalone",
        "    run(",
        "        start_job_handler=process_job,",
        "        input_schema_handler=INPUT_SCHEMA",
        "        # config, agent_identifier, network loaded from env vars automatically",
        "    )",
        ""
    ]
    template = "\n".join(template_parts)
    
    # Write file
    with open(output_file, 'w') as f:
        f.write(template)
    
    print(f"\n✅ Generated agent file: {output_file}")
    print("\nNext steps:")
    print(f"  1. Install required dependencies (if any)")
    if database:
        db_packages = {
            "postgresql": "psycopg2-binary",
            "mongodb": "pymongo",
            "redis": "redis"
        }
        if database in db_packages:
            print(f"     - Database: pip install {db_packages[database]}")
    if framework:
        print(f"     - Framework: pip install {framework}")
    print("  2. Set environment variables:")
    print("     - AGENT_IDENTIFIER (required for API mode)")
    print("     - PAYMENT_API_KEY (required for API mode)")
    print("     - PAYMENT_SERVICE_URL (optional, defaults to production)")
    print("     - NETWORK (optional, defaults to 'Preprod')")
    if database:
        print(f"     - Database connection variables (see {output_file})")
    print(f"  3. Run: masumi run {output_file}")
    print(f"     Or: masumi run {output_file} --standalone")
    print()

