#!/usr/bin/env python3
"""
test01 - Main Entry Point
Generated by masumi scaffold

This is the entry point for your Masumi agent.
Run this file to start the agent server.
"""
import os
from masumi import run
from agent import process_job
from agent import get_db

# Define input schema
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "text",
            "type": "string",
            "name": "Text Input",
            "data": {
                "description": "Text to process"
            },
            "validations": [
                {"validation": "required", "value": "true"}
            ]
        }
    ]
}

# Main entry point
if __name__ == "__main__":
    # Database collections are created automatically in MongoDB
    # No initialization needed
    # Config and identifiers loaded from environment variables
    # Default mode is API - use --standalone flag to run standalone
    run(
        start_job_handler=process_job,
        input_schema_handler=INPUT_SCHEMA
        # config, agent_identifier, network loaded from env vars automatically
    )
